# Generated by Django 4.2.6 on 2023-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='avaliable_founds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payables',
            name='waiting_founds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='1232-2222-2222-2222', max_length=18),
        ),
    ]
