# Generated by Django 4.2.6 on 2023-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payables_avaliable_founds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='1232-2222-2222-2222', max_length=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
