# Generated by Django 4.2.6 on 2023-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_card_number_alter_transaction_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cvv',
            field=models.CharField(default='123', max_length=3),
        ),
    ]
